# Generated by Django 4.1.3 on 2023-01-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_adminregister_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=255)),
                ('Oldprice', models.CharField(max_length=255)),
                ('Newprice', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='product/')),
                ('Catagory', models.CharField(max_length=255)),
            ],
        ),
    ]
