# Generated by Django 4.1.3 on 2023-01-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=255)),
                ('Total', models.CharField(max_length=255)),
                ('Status', models.CharField(default='pending', max_length=255)),
                ('Prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product_tb')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register_tb')),
            ],
        ),
    ]
