# Generated by Django 4.1.3 on 2023-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_payment_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newprice', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='product/')),
                ('Quantity', models.CharField(max_length=255)),
            ],
        ),
    ]
